Update GitHub Actions

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,5 +30,14 @@ jobs:
           cache: true
 
       - name: Tests
+        id: test
         run: make testacc
+        continue-on-error: true
+
+      - name: Publish Test Summary Results
+        run: npx github-actions-ctrf ctrf-report.json
+      
+      - name: Handle failure
+        if: ${{ steps.test.outcome == 'failure' }}
+        run: echo "Tests failed for RabbitMQ v${{ matrix.node }}." && exit 90
         
